src/js/fields/basic/ObjectField.js
As discussed in https://github.com/gitana/alpaca/issues/249 there is no
guarantee that fields will be rendered in the order they are delcared in
the schema. By adding an `order` option, users can optionally choose
whether or not to enforce a certain order without having to create a
layout.
=> Adding order option to ObjectField.

src/js/AbstractTemplateEngine.js, src/js/Alpaca.js
The AbstractTemplateEngine and compileViewTemplate functions had
different opinions on what an uri is. Replaced with the already
existing Alpaca.isUri function.
=> Using Alpaca.isUri where applicable

src/js/Form.js
When  rendering Alpaca.Form, the call to `parentEl.find` was undefined
because `parentEl` is not a jQuery object. A few lines later, `parentEl` was
explicitly being wrapped as a jQuery object. This fix simply wraps it
higher in the method to fix the call to `find`.
=> Fixing for a rendering bug in Alpaca.Form.

gulpfile.js
Fails to build on Windows due to path seperator difference.
=> Build on Windows fails.

src/js/fields/advanced/CurrencyField.js
This is causing an Uncaught TypeError to be thrown.
=> Bug - Typo in Currency Field js

gulpfile.js, site/docs/api/i18n.md, src/js/messages/i18n/cs_CZ.js
Add Czech locale. There are some problems that prevent correct translation.
- Plural forms
- eg: "stringTooShort":
- "Toto pole musí obsahovat nejmeně 0 znaků"
- "Toto pole musí obsahovat nejmeně 1 znak"
- "Toto pole musí obsahovat nejmeně 2 znaky" (2, 3, 4)
- "Toto pole musí obsahovat nejmeně 5 znaků" (>= 5)
- Default patterns
- eg: invalid phone should be `"invalidPhone": "Invalid Phone Number, e.g. {0}"`, where `{0}` is the mask or is based on the mask. Phone number `"(123) 456-9999"` is always invalid for czech republic. There should be eg: `"(+420) 800 123 456"`, where the part `"(+420)"` is optional.
=> Add Czech (cs_CZ) locale

src/js/fields/basic/NumberField.js
Required numbers are not validating correctly. Currently, if nothing is entered into a number field, this.getValue() evaluates to "NaN", which currently passes validation because "NaN" is not empty.
This fix changes it so that the control value is evaluated as empty before trying to cast it to a number.
=> Fix validation for required numbers

src/js/ControlField.js, src/js/fields/basic/CheckBoxField.js
This allows checkboxes to be used with arrays while specifying the enumeration inside of the array's items, which is consistent with JSON schema v4.
The following code throws an error with Alpaca 1.5.15 but works with this patch:
```
{
"schema": {
"type": "object",
"properties": {
"checkboxArrayEnum": {
"type": "array",
"items": {
"type": "string",
"enum": [
"option 1",
"option 2",
"option 3"
]
}
}
},
"required": [
"checkboxArrayEnum"
]
},
"options": {
"fields": {
"checkboxArrayEnum": {
"label": "Checkbox Array Enum",
"type": "checkbox"
}
}
}
}
```
=> Allow checkbox array item enums

src/js/fields/advanced/ColorField.js
If you use a color field inside an array, all spectrum instances are initialized with the same color regardless of the underlying data.
This PR changes spectrum init to use a separate options object for every spectrum instance.
=> Fix color field when used inside arrays

site/demos/bootstrap/multi-column-layouts/index.md
The links for the data, schema & options json data were scoping to the
wiki pages local folder for the anchor links, but the json payload had
the correct links so I copied those in.
=> Fixed broken links for example data

src/js/fields/advanced/AddressField.js
I noticed that my address street fields were not initializing with new empty fields.  This small change appears to fix that.
=> Very Basic: Fixed initialization of the double empty street field in address

src/js/fields/advanced/ColorField.js
Avoid adding spectrum options when spectrum not available.
Because this avoid setting inputType to color on a array with color field
=> Avoid adding spectrum options when no spectrum

src/js/fields/advanced/UploadField.js
Currently if no errorHandler function is set in the options for the Upload field, and a server error occurs when uploading a file, there is a JavaScript error `messages.join is not a function`.  The errorHandler function is expecting an array of strings to join and alert with. 
Additional information about this can be found with #455
=> Bug with errorHandler function in Upload field

src/js/fields/basic/TextField.js
Auto-completion in an array field works only for the first item as shown in https://gist.github.com/gertingold/8a2533f1899e12065a9ef9fafc7c72bb. The problem appears to be due to multiple initialization of the bloodhound engine. This PR proposes to prevent multiple initialization.
The diff looks quite messy because the indentation of a relatively large code block was changed. It is therefore worth pointing out the relevant changes:
* new line 190: check whether `tDatasets` was already initialized 
* new line 285: mark `tDatasets` as initialized
=> auto-completion in array field

package.json
Version 10.0.0 of `jsdom` has a new API and was released earlier today. Due to the new API, running `gulp site`, now causes errors. Until the code is updated to work with the new API, the version of `jsdom` in `package.json`should be set to a version lower than 10.0.0.
> The old jsdom API, from before v10, is hard to use and understand, and has bad defaults. But for now, it still has more features than the new API introduced in v10. As such, it is still supported, until we can port over all important features (notably custom resource loading) to the new API.
From: https://github.com/tmpvar/jsdom/blob/master/lib/old-api.md
=> Set valid package version for 'jsdom'

src/css/alpaca-bootstrap.css, src/js/fields/basic/ArrayField.js, src/js/views/web.js, src/templates/web-edit/container-array-toolbar.html, src/templates/web-edit/container-array.html
By setting the new option "toolbarPosition" to "bottom",  the toolbar will be generated at the bottom
of the container
=> Add support for a toolbar being placed at the bottom of a container

package.json
See #489 
The lack of main field in package.json makes it harder for webpack users who want to keep package.json as the main descriptionFile
=> Adding main field to package.json

src/js/fields/basic/ArrayField.js
If user resets form, array items remain. (Only internal array item fields are cleared). Is it bug or feature? I changed code to remove array items during form cleaning.
=> Cleaning form (array field).

site/docs/fields/phone.md
My team was trying to add a phone field and couldn't figure out why it didn't work. Finally I checked the code and noticed the `.mask` function and realized we needed the dependency jquery.maskedinput
=> Added info about required phone field dependency jquery.maskedinput

.gitignore, .testem.json, site/_includes/JB/setup, site/docs/api/usage.md, site/docs/fields/array.md, src/css/alpaca-bootstrap.css, src/js/Alpaca.js, src/js/fields/basic/ArrayField.js, src/templates/web-edit/container-array-item.html, tests.mustache
Added a property for array options: dragAndDrop
If dragAndDrop is true, users can drag and drop items in the same array. Actionbar will be hidden, and instead two buttons will show up on the right side of each array item. They are the move button and the remove button respectively.
Fixed styling for array items when actionbar is on the right or left.
Updated the setup file for jekyll-bootstrap to fix a problem when parsing ASSET_PATH.
Updated testem configs for it to work properly.
=> Drag and drop for array items
